name: Build and Flash ESP32 Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build ESP32 Firmware
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    
    - name: Build firmware
      run: |
        pio run --target build
    
    - name: Upload firmware (optional)
      run: |
        pio run --target upload
      env:
        PIOUPLOADPORT: /dev/ttyUSB0  # Adjust this to match your serial port
